### ISSUE TITLE
Clarification of Arity

### ISSUE THREAD

**Issue by Technohacker** [Schwenger/RustTyC#5]
Hello!
I'm a little confused on the concept of arity in type systems and specifically `Partial::least_arity`. I couldn't understand it with a cursory glance over the blog post and the README, especially since I don't have much prior understanding in implementing type systems. It'd be great if I could get a short description on how it fits together

Thanks!

**Comment by Schwenger** [comment]
Hey,

thanks for your interest.  I'll gladly elaborate.
When imposing constraints on keys and during the type inference, the type checker collects as much information as it can.  Some of this information is preliminary and might be refined later on.  `Partial::least_arity` is a prime example of this; it states how many children the type checker _thinks_ a type has.  
Here, tuples are the most canonical example.  Suppose you have the following code:
```rust
let a = someFunctionWithoutTypeInformation()
let b = someFunctionWithoutTypeInformation()
let _ = a.2 // access the third child
let _ = b.5 // access the sixth child
let c = a + b // e.g. piece-wise addition of tuples with same arity with type. T×T → T
```
Here, you'd first assign `a` and `b` a new key each.  Next, you would access the third child of `a` and sixth of `b`, e.g. via `TypeChecker:: get_child_key`.  Last, you'd meet the keys of `a` and `b` for the addition.  This meet operation then receives two partials as arguments, representing `a` and `b`.  When inquiring the `least_arity` of the partial for `a`, the type checker would tell you, that it has at least three children, maybe even more.  Similarly, the `least_arity` of the partial for `b` is 6.  The result of the meet operation is again a partial.  Here, you have to make sure that the `least_arity` of the result is at least 6.  The reason is that we know that the result of the addition yields something that has at least as many children as each operand.

I hope that helps, let me know if I can help further.

**Comment by Technohacker** [comment]
This was useful, thanks!
So to test my understanding, say i had a C-like structure type, where there are multiple key-value types as children. And say i defined a union operation between these Map types (as i call them), where the resulting type has keys defined as the union of the two key sets (name clashes are treated as an error)

I assume i would treat the specific map types as having fixed arity (equal to the number of keys), and the generic map type having variable arity

That being said, I assume arity is mainly useful for types with some kind of numerical indexing? Taking the Tuple type example again, you could do some form of bounds checking when indexing a partially resolved Tuple, whereas for the Map type the number of children couldn't be used for many checks?

**Comment by Schwenger** [comment]
Yeah, precisely!

The major point behind the arity is numerically indexed types, i.e., tuples, but they can somewhat clumsily work for structs, too. 
For tuples, I don't think bounds checks make too much sense since there is no natural limit on the number of children.  
For structs, it would make a whole lot of sense, though.  In a stroke of happy coincidence, my colleague implemented some more changes for more native struct-capabilities in RustTyC.  Feel free to check out his branch and PR, [named-children](https://github.com/Schwenger/RustTyC/tree/named-children), and everything else he's up to.  We'll soon merge it into the main code base as well, probably with some refractoring to reduce complexity and clarify a couple concepts like Partials.

**Comment by Technohacker** [comment]
Oh that's lovely, I'll look through the PR for more info. Thanks for the explanation and the crate as a whole! :D
